name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug runner info
      run: |
        echo "PATH=$PATH"
        which tar || echo "tar not found"
        tar --version || echo "tar version check failed"

    - name: Checkout repository using Git CLI (workaround)
      run: |
        git --version
        git clone https://github.com/${{ github.repository }} ${{ github.workspace }}

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk wget tar

    - name: Install Python dependencies
      run: |
        pip3 install --upgrade cython==0.29.33 buildozer

    - name: Setup Android SDK command line tools
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        rm cmdline-tools.zip
        mv cmdline-tools latest

    - name: Accept licenses
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

    - name: Install SDK components
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK with Buildozer
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
