name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: androidsdk/android-sdk:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip3 install --upgrade cython==0.29.33 buildozer

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk

