name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-11-jdk python3-pip python3-setuptools python3-dev build-essential libffi-dev libssl-dev

    - name: Download and Install Android SDK
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q sdk.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "platform-tools"

    - name: Add Android SDK to PATH
      run: |
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Init and configure Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

        # Remove duplicate lines if present
        sed -i '/^requirements/d' buildozer.spec
        sed -i '/^android.permissions/d' buildozer.spec
        sed -i '/^android.sdk_path/d' buildozer.spec

        echo "requirements = python3,kivy,requests" >> buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec
        echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
