name: Build APK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 36.0.0
          ndk-version: 25.2.9519653

      - name: Install dependencies and build APK
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade buildozer
          buildozer android clean
          buildozer android debug

      - name: Build APK
        run: buildozer android debug
