name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip python3-setuptools python3-dev build-essential libffi-dev libssl-dev

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip sdk.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/.local/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_PATH

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Clean Buildozer Cache
      run: |
        buildozer appclean || true
        rm -rf ~/.buildozer

    - name: Init Buildozer (if needed)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        sed -i '/^requirements *=/d' buildozer.spec
        echo "requirements = python3,kivy,requests" >> buildozer.spec
        sed -i '/^android.permissions *=/d' buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
